version: 2

python:
   install:
   - requirements: doc/requirements.txt

sphinx:
  configuration: doc/conf.py
  fail_on_warning: true
  
formats:
   - pdf

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

submodules:
  include: all